version: "3.8"

services:
  excalidraw: 
    image: kiliandeca/excalidraw
    healthcheck:
      disable: true
    ports:
      - "5189:80"
    environment:
      BACKEND_V2_GET_URL: http://localhost:5199/api/v2/scenes/
      BACKEND_V2_POST_URL: http://localhost:5199/api/v2/scenes/
      LIBRARY_URL: https://libraries.excalidraw.com
      LIBRARY_BACKEND: https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      SOCKET_SERVER_URL: http://localhost:5179/
      STORAGE_BACKEND: "http"
      HTTP_STORAGE_BACKEND_URL: "http://localhost:5199/api/v2"

  excalidraw-storage-backend:
    build: .
    ports:
      - "5199:8080"
    environment:
      STORAGE_URI: mongodb://admin:admin@localhost:5159/excalidraw

  excalidraw-room:
    image: excalidraw/excalidraw-room
    ports:
      - "5179:80"
  
  mongodb:
    image: mongo
    container_name: mongodb_for_excalidraw
    restart: always
    ports:
      - 5159:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
